apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: serverapp
spec:
  selector:
    matchLabels:
      app: serverapp
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: serverapp
        tier: backend
        track: stable
    spec:
      containers:
        - name: serverapp
          image: "docker.io/polaksh/devops-exam-server:latest"
          ports:
            - name: http
              containerPort: 9090
