kind: Service
apiVersion: v1
metadata:
  name: server-side
spec:
  selector:
    app: server-side
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server-side
spec:
  selector:
    matchLabels:
      app: server-side
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: server-side
        tier: backend
        track: stable
    spec:
      containers:
        - name: server-side
          image: "docker.io/polaksh/devops-exam-server:latest"
          ports:
            - name: http
              containerPort: 9090
