apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-server
  labels:
    app: my-server
spec:
  template:
    metadata:
      labels:
        app: my-server
        tier: web
    spec:
      containers:
      - name: server-side
        image: docker.io/polaksh/devops-exam-server
        ports:
        - containerPort: 9090
